### ISSUE TITLE
Error: command `git` failed: exit status 128 

### ISSUE THREAD

**Issue by p0o** [chronotc/monorepo-diff-buildkite-plugin#66]
Hi, i'm dealing with this problem for hours now so appreciate some comments here. I'm using something very similar to the default detailed template provided in the README. The problem is that whenever I try to trigger it using a buildkite setup, I'm facing this error:

```
$ /etc/buildkite-agent/plugins/github-com-chronotc-monorepo-diff-buildkite-plugin-v2-0-4/hooks/command
https://github.com/chronotc/monorepo-diff-buildkite-plugin/releases/download/v2.0.4/monorepo-diff-buildkite-plugin-linux
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   644  100   644    0     0   5750      0 --:--:-- --:--:-- --:--:--  5750
100 3302k  100 3302k    0     0  11.6M      0 --:--:-- --:--:-- --:--:-- 11.6M
INFO[0000] --- :one: monorepo-diff v2.0.4
INFO[2021-06-04T10:25:40Z] Running diff command: git diff --name-only $(head -n 1 ~/last_successful_build)
FATA[2021-06-04T10:25:40Z] diff command failed: command `git` failed: exit status 128
🚨 Error: The command exited with status 1
```

Here is my pipeline.yml and if I change the diff to `git diff --name-only HEAD~1` it is working without error.
I can aslo confirm that the file `last_successful_release`  exist, contains the hash of the branch point and running the command `git diff --name-only $(head -n 1 ~/last_successful_build)` in the server (using buildkite user) works perfectly fine.

```
steps:
  - label: "Triggering pipelines"
    plugins:
      - chronotc/monorepo-diff#v2.0.4:
          # here is the problem, more specifically the lines inside the $()
          diff: "git diff --name-only $(head -n 1 ~/last_successful_build)"
          interpolation: false
          watch:
            - path:
                - "repo1/"
              config:
                command: "buildkite-agent pipeline upload repo1/.buildkite/pipeline.yml"
                label: "repo1"
            - path:
                - "repo2/"
              config:
                command: "buildkite-agent pipeline upload repo2/.buildkite/pipeline.yml"
                label: "repo2"
            - path:
                - "repo3/"
              config:
                command: "buildkite-agent pipeline upload repo3/.buildkite/pipeline.yml"
                label: "repo3"
  - wait
  - label: "Mark Build"
    # This is working fine
    command: "echo $(git rev-parse HEAD) > ~/last_successful_build"
```

**Comment by phazel** [comment]
I'm having this exact same issue, though I'm using `buildkite-agent meta-data` to store the hash. It seems it doesn't matter where the hash comes from, as long as the hash is being programmatically applied in the command rather than literally written, it will cause this failure. I've tried setting an environment variable at various levels (step, pipeline, etc.) but that also fails, since using the environment variable in the diff command is still passing a dynamic argument rather than a hardcoded one. Using a literal hash string here also works. It seems it's the string interpolation that's the issue. Hope that helps with figuring it out.

**Comment by adikari** [comment]
This generally happens when your git index is corrupted. This is to the issue with the plugin but with your git repo. Can you try remove `.git/index` file from your repo then run `git reset`. 

```
rm .git/index
git rest
```

Let me know how you go

**Comment by ohookins** [comment]
It feels like the pre-plugin hook doesn't work:
```
          hooks:
            - command: "echo $(git rev-parse HEAD) > last_successful_build"
```
I can't see any evidence of this executing in my build, and I've used almost identical configuration to the example.

**Comment by adikari** [comment]
@ohookins can you please provide more details of your setup. It feels like the issue is not with the plugin but with your setup. That's just my guess though. The reason I am saying that is, I am using a similar setup for a few of my pipelines and they are fine. 

Details of:
- your build pipeline configuration
- how your pre command hook is set up

Can you also try to run the same command in a pipeline without using the plugin?

**Comment by ohookins** [comment]
The build pipeline was exactly the same as in the example - that's what I started with. Same as the pre-command hook.

```
Running plugin monorepo-diff command hook | 0s
-- | --
  | $ /etc/buildkite-agent/plugins/github-com-chronotc-monorepo-diff-buildkite-plugin-v2-1-1/hooks/command
  | https://github.com/chronotc/monorepo-diff-buildkite-plugin/releases/download/v2.1.1/monorepo-diff-buildkite-plugin-linux-amd64
  | % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
  | Dload  Upload   Total   Spent    Left  Speed
  | 100   681  100   681    0     0   8512      0 --:--:-- --:--:-- --:--:--  8512
  | 100 3138k  100 3138k    0     0  11.0M      0 --:--:-- --:--:-- --:--:-- 11.0M
  | INFO[0000] --- :one: monorepo-diff v2.1.1
  | INFO[2021-11-16T00:50:08Z] Running diff command: git diff --name-only $(head -n 1 last_successful_build)
  | FATA[2021-11-16T00:50:08Z] diff command failed: command `git` failed: exit status 128
  | 🚨 Error: The command exited with status 1
  | user command error: The plugin monorepo-diff command hook exited with status 1
```

Right now I have the diff command run directly in the `diff` config section rather than a pre-command hook, so I know that the command does work outside of that context. Evidently it just never runs it as the pre-command hook (which in this case would populate the last_successful_build file).

**Comment by adikari** [comment]
The `last_successful_build` is a placeholder for you to replace with the commit you want to diff against. I don't believe there is such a variable set by buildkite. Can you explain what you are trying to do?

**Comment by ohookins** [comment]
@adikari it's right there in the examples in the readme. It's not a buildkite variable, it's a file written to by a plugin hook that is not functioning. That's the problem.

https://github.com/chronotc/monorepo-diff-buildkite-plugin/blob/master/README.md?plain=1#L45

**Comment by adikari** [comment]
@ohookins i might need some time. I will have a look on what's going on.

**Comment by nept** [comment]
Hi 👋,
Anything here? I'm facing the exact same issue from the test exemple. Thanks.

**Comment by xzyfer** [comment]
I suspect this is because the `$` needs to be escaped. Try `command: "echo \$(git rev-parse HEAD) > last_successful_build"`

**Comment by arshu16** [comment]
Had the same issue. In my case, it turned out to be comparing against an empty commit.
